<template>
  <div class="relative rounded-xl overflow-hidden mb-8">
    <!-- Animated Border -->
    <div class="absolute inset-0 rounded-xl p-[2px] animated-border">
      <div :class="[
        'w-full h-full rounded-xl transition-all duration-300',
        isDarkMode
          ? 'bg-gradient-to-br from-gray-900 to-gray-800 shadow-purple-900/20'
          : 'bg-gradient-to-br from-white to-blue-50 shadow-blue-100/30',
        'shadow-xl'
      ]"></div>
    </div>

    <!-- Content Container -->
    <div class="relative z-10 rounded-xl">
      <!-- AI Header -->
      <div :class="[
        'flex items-center gap-3 p-4 border-b',
        isDarkMode ? 'border-gray-700' : 'border-gray-200'
      ]">
      <div :class="[
        'w-8 h-8 rounded-full flex items-center justify-center',
        isDarkMode ? 'bg-purple-600' : 'bg-blue-500'
      ]">
        <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"></path>
        </svg>
      </div>
      <div>
        <h3 :class="[
          'font-semibold text-lg',
          isDarkMode ? 'text-white' : 'text-gray-900'
        ]">AI Performance Analysis</h3>
        <p :class="[
          'text-sm',
          isDarkMode ? 'text-gray-400' : 'text-gray-600'
        ]">Analyzing your Lighthouse audit data</p>
      </div>
      <!-- Loading indicator -->
      <div v-if="isLoading" class="ml-auto">
        <div :class="[
          'animate-spin rounded-full h-6 w-6 border-2 border-t-transparent',
          isDarkMode ? 'border-purple-400' : 'border-blue-400'
        ]"></div>
      </div>
    </div>

    <!-- Content Area -->
    <div class="p-6">
      <!-- Loading State -->
      <div v-if="isLoading" class="space-y-4">
        <div :class="[
          'flex items-center gap-3 p-4 rounded-lg',
          isDarkMode ? 'bg-gray-800/50' : 'bg-blue-50/50'
        ]">
          <div :class="[
            'animate-pulse w-2 h-2 rounded-full',
            isDarkMode ? 'bg-purple-400' : 'bg-blue-400'
          ]"></div>
          <span :class="[
            'text-sm',
            isDarkMode ? 'text-gray-300' : 'text-gray-700'
          ]">Processing your performance data...</span>
        </div>

        <!-- Skeleton lines -->
        <div class="space-y-3">
          <div v-for="i in 3" :key="i" :class="[
            'h-4 rounded animate-pulse',
            isDarkMode ? 'bg-gray-700' : 'bg-gray-200'
          ]" :style="{ width: `${85 - i * 10}%` }"></div>
        </div>
      </div>

      <!-- Summary Content -->
      <div v-else-if="summary" class="space-y-4">
        <div :class="[
          'prose prose-sm max-w-none',
          isDarkMode ? 'prose-invert' : ''
        ]">
          <!-- Format each line as a proper paragraph or list item -->
          <div v-for="(line, index) in formattedLines" :key="index" class="mb-3">
            <p v-if="line.type === 'paragraph'" :class="[
              'leading-relaxed',
              isDarkMode ? 'text-gray-200' : 'text-gray-700'
            ]" v-html="line.content"></p>

            <div v-else-if="line.type === 'bullet'" :class="[
              'flex items-start gap-2 ml-4',
              isDarkMode ? 'text-gray-300' : 'text-gray-600'
            ]">
              <span :class="[
                'w-1.5 h-1.5 rounded-full mt-2 flex-shrink-0',
                isDarkMode ? 'bg-purple-400' : 'bg-blue-400'
              ]"></span>
              <span class="leading-relaxed" v-html="line.content"></span>
            </div>
          </div>
        </div>

        <!-- AI Footer -->
        <div :class="[
          'flex items-center gap-2 pt-4 border-t text-xs',
          isDarkMode ? 'border-gray-700 text-gray-500' : 'border-gray-200 text-gray-500'
        ]">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
          </svg>
          Generated by AI • Based on your performance audit data
        </div>
      </div>

      <!-- Empty State -->
      <div v-else :class="[
        'text-center py-8',
        isDarkMode ? 'text-gray-400' : 'text-gray-500'
      ]">
        <svg class="w-12 h-12 mx-auto mb-4 opacity-50" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"></path>
        </svg>
        <p>Getting AI-powered insights</p>
      </div>
    </div>
  </div>
</div>
</template>

<script setup>
import { computed, ref, onMounted } from 'vue'

const props = defineProps({
  scores: Object,
  allRunsData: Array,
  opportunities: Array,
  isDarkMode: Boolean,
  compareTables: {
    type: Boolean,
    default: false
  }
})

const summary = ref('');
const isLoading = ref(false);

const formattedLines = computed(() => {
  if (!summary.value) return [];

  return summary.value
    .split('\n')
    .filter(line => line.trim())
    .map(line => {
      const trimmed = line.trim();
      if (trimmed.startsWith('-') || trimmed.startsWith('•')) {
        return {
          type: 'bullet',
          content: trimmed.substring(1).trim()
        };
      }
      return {
        type: 'paragraph',
        content: trimmed
      };
    });
});

async function fetchSummary() {
  isLoading.value = true;
  try {
    const body = props.compareTables ?
      {
        allRunsData: props.allRunsData,
        tableComparison: true
      } :
      {
        coreMetrics: props.allRunsData,
        opportunities: props.opportunities,
        scores: props.scores,
        tableComparison: false
      }
    const res = await fetch('/api/ai-summary', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body)
    });
    if (res.ok) {
      const { summary: text } = await res.json();
      summary.value = text;
      console.log('AI Response:', summary.value);
    }
  } catch (e) {
    console.error('Failed to get summary', e);
  } finally {
    isLoading.value = false;
  }
}

onMounted(async () => {
  if (props.allRunsData.length > 0) {
    setTimeout(async () => {
      await fetchSummary();
    }, 5000);
  }
});
</script>

<style scoped>
@keyframes border-spin {
  0% {
    background: linear-gradient(0deg, #8b5cf6, #ec4899, #3b82f6, #10b981, #f59e0b, #ef4444);
  }
  16.66% {
    background: linear-gradient(60deg, #8b5cf6, #ec4899, #3b82f6, #10b981, #f59e0b, #ef4444);
  }
  33.33% {
    background: linear-gradient(120deg, #8b5cf6, #ec4899, #3b82f6, #10b981, #f59e0b, #ef4444);
  }
  50% {
    background: linear-gradient(180deg, #8b5cf6, #ec4899, #3b82f6, #10b981, #f59e0b, #ef4444);
  }
  66.66% {
    background: linear-gradient(240deg, #8b5cf6, #ec4899, #3b82f6, #10b981, #f59e0b, #ef4444);
  }
  83.33% {
    background: linear-gradient(300deg, #8b5cf6, #ec4899, #3b82f6, #10b981, #f59e0b, #ef4444);
  }
  100% {
    background: linear-gradient(360deg, #8b5cf6, #ec4899, #3b82f6, #10b981, #f59e0b, #ef4444);
  }
}

.animated-border {
  animation: border-spin 3s linear infinite;
  background: linear-gradient(45deg, #8b5cf6, #ec4899, #3b82f6, #10b981, #f59e0b, #ef4444);
  background-size: 300% 300%;
}
</style>
